import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import pg from "pg";
import { Decimal } from "decimal.js";

const url=process.env.TEST_DATABASE_URL;
const maybeTest=url?test:test.skip;
maybeTest("TEST-POS-001..012 Portfolio HTTP PostgreSQL classification aggregation and provenance",async()=>{
 const{createApp}=await import("../../apps/api/src/app.js");const server=createApp().listen(0);const db=new pg.Client({connectionString:url});await db.connect();
 const accountId=crypto.randomUUID();
 try{
  await db.query(`INSERT INTO accounts(id,name,type,base_currency,status) VALUES($1,'Portfolio E2E','MANUAL','BRL','ACTIVE')`,[accountId]);
  const address=server.address();assert.ok(address&&typeof address!=="string");const base=`http://127.0.0.1:${address.port}`;
  const [strategiesResponse,instrumentsResponse]=await Promise.all([fetch(base+"/v1/strategies").then(r=>r.json()),fetch(base+"/v1/strategies/instruments").then(r=>r.json())]);
  const strategies=(strategiesResponse as {items:Array<{id:string;code:string}>}).items;const instruments=(instrumentsResponse as {items:Array<{id:string;symbol:string}>}).items;
  const strategy=(code:string)=>{const item=strategies.find(x=>x.code===code);assert.ok(item);return item.id;};const instrument=(symbol:string)=>{const item=instruments.find(x=>x.symbol===symbol);assert.ok(item);return item.id;};
  async function create(payload:Record<string,unknown>){const response=await fetch(base+"/v1/operations",{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({...payload,accountId})});if(response.status!==201)assert.fail(`create failed: ${response.status} ${await response.text()}`);return response.json() as Promise<{id:string}>;}
  const holding1=await create({strategyId:strategy("STR-001"),template:{type:"EQUITY_HOLDING",version:1},openedAt:"2026-01-01T10:00:00Z",legs:[{instrumentId:instrument("EMBR3"),side:"BUY",quantity:"150",entryPrice:"38.23",currency:"BRL"}]});
  const holding2=await create({strategyId:strategy("STR-002"),template:{type:"EQUITY_HOLDING",version:1},openedAt:"2026-01-02T10:00:00Z",legs:[{instrumentId:instrument("EMBR3"),side:"BUY",quantity:"1",entryPrice:"40",currency:"BRL"}]});
  const spot=await create({strategyId:strategy("STR-005"),template:{type:"CRYPTO_SPOT",version:1},instrumentId:instrument("BTC"),side:"BUY",quantity:"0.00031",unitPrice:"63000.38",currency:"USD",openedAt:"2026-02-01T10:00:00Z"});
  const pair=await create({strategyId:strategy("STR-003"),template:{type:"EQUITY_PAIR",version:1},openedAt:"2026-03-01T10:00:00Z",legs:[{instrumentId:instrument("PTBR4"),side:"BUY",quantity:"166",entryPrice:"18.32",currency:"BRL"},{instrumentId:instrument("SMIG3"),side:"SELL",quantity:"330",entryPrice:"7.35",currency:"BRL"}]});
  const future=await create({strategyId:strategy("STR-004"),template:{type:"FUTURES_ROUND_TRIP",version:1},instrumentId:instrument("WDOL26"),openingSide:"SELL",contracts:"10",entryPrice:"5336",exitPrice:"5330",currency:"BRL",openedAt:"2026-04-01T10:00:00Z",closedAt:"2026-04-01T11:00:00Z"});
  const derivative=await create({strategyId:strategy("STR-006"),template:{type:"CRYPTO_DERIVATIVE",version:1},instrumentId:instrument("BTC"),side:"SELL",investedCapital:"100",leverage:"50",entryPrice:"69358.32",exitPrice:"59862.15",currency:"USD",openedAt:"2026-04-02T10:00:00Z",closedAt:"2026-04-02T11:00:00Z"});
  const lpValues=[{current:"100.10",fees:"0"},{current:"100",fees:"0"},{current:"428.12",fees:"36.22"}];const lpIds:string[]=[];
  for(let index=0;index<lpValues.length;index++){const lp=await create({strategyId:strategy("STR-007"),template:{type:"DEFI_LP",version:1},componentInstrumentIds:[instrument("WBTC"),instrument("SOL")],investedAmount:index===2?"450.31":"100",currency:"USD",openedAt:`2026-05-0${index+1}T10:00:00Z`});lpIds.push(lp.id);const first=lpValues[index]!;const response=await fetch(`${base}/v1/operations/${lp.id}/snapshots`,{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({currentPositionValue:first.current,unclaimedFees:first.fees,currency:"USD",observedAt:`2026-06-0${index+1}T10:00:00Z`})});assert.equal(response.status,201);if(index===2){const latest=await fetch(`${base}/v1/operations/${lp.id}/snapshots`,{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({currentPositionValue:"428.12",unclaimedFees:"36.22",currency:"USD",observedAt:"2026-07-28T10:00:00Z"})});assert.equal(latest.status,201);}}
  const positionsResponse=await fetch(`${base}/v1/portfolio/positions?accountId=${accountId}`);assert.equal(positionsResponse.status,200);const positions=(await positionsResponse.json() as {items:any[]}).items;
  const holdings=positions.filter(p=>p.kind==="EQUITY_HOLDING"||p.kind==="SPOT_HOLDING");assert.equal(holdings.length,3);assert.equal(holdings.filter(p=>p.instrumentId===instrument("EMBR3")).length,2);assert.deepEqual(new Set(holdings.filter(p=>p.instrumentId===instrument("EMBR3")).map(p=>p.strategyId)),new Set([strategy("STR-001"),strategy("STR-002")]));
  assert.equal(holdings.some(p=>p.instrumentId===instrument("PTBR4")||p.instrumentId===instrument("SMIG3")||p.instrumentId===instrument("WBTC")||p.instrumentId===instrument("SOL")),false);const btc=holdings.find(p=>p.kind==="SPOT_HOLDING");assert.ok(btc);assert.ok(new Decimal(btc.quantity).eq("0.00031"));assert.deepEqual(btc.provenance.operationIds,[spot.id]);
  const pairPosition=positions.find(p=>p.kind==="PAIR_EXPOSURE");assert.ok(pairPosition);assert.equal(pairPosition.sourceOperationId,pair.id);assert.equal(pairPosition.legs.length,2);assert.equal(pairPosition.grossExposure.value,"5466.62");
  const lpPosition=positions.find(p=>p.kind==="DEFI_LP"&&p.sourceOperationId===lpIds[2]);assert.ok(lpPosition);assert.equal(lpPosition.economicValue.value,"464.34");assert.equal(lpPosition.provenance.snapshotIds.length,1);assert.deepEqual(lpPosition.components.map((x:any)=>x.symbol),["SOL","WBTC"]);
  assert.equal(positions.some(p=>p.sourceOperationId===future.id||p.sourceOperationId===derivative.id),false);
  const historical=(await fetch(`${base}/v1/portfolio/historical-results?accountId=${accountId}`).then(r=>r.json()) as {items:any[]}).items;assert.equal(historical.length,2);const futureResult=historical.find(x=>x.operationId===future.id);const derivativeResult=historical.find(x=>x.operationId===derivative.id);assert.ok(futureResult&&derivativeResult);assert.equal(futureResult.grossPnl.value,"600.00");assert.equal(futureResult.netPnl.status,"INCOMPLETE");assert.equal(derivativeResult.grossPnl.status,"AVAILABLE");assert.equal(derivativeResult.netPnl.status,"INCOMPLETE");
  const summary=await fetch(`${base}/v1/portfolio?accountId=${accountId}`).then(r=>r.json()) as any;assert.deepEqual(summary.currencyBuckets.map((x:any)=>x.currency),["BRL","USD"]);assert.deepEqual(summary.globalTotal,{status:"INCOMPLETE",value:null,reason:"MISSING_FX_RATE"});const usd=summary.currencyBuckets.find((x:any)=>x.currency==="USD");assert.ok(usd);assert.equal(usd.knownMarketValue.status,"INCOMPLETE");assert.equal(usd.knownMarketValue.knownValue,"664.44");assert.deepEqual(usd.knownMarketValue.coverage,{totalComponents:4,availableComponents:3,missingComponents:1});
  const legacyPair=await fetch(`${base}/v1/operations/position/${accountId}/${instrument("PTBR4")}`);assert.equal(legacyPair.status,404);const legacyHolding=await fetch(`${base}/v1/operations/position/${accountId}/${instrument("EMBR3")}`);assert.equal(legacyHolding.status,200);const legacy=await legacyHolding.json() as {quantity:string};assert.ok(new Decimal(legacy.quantity).eq("151"));
  assert.deepEqual(new Set([holding1.id,holding2.id]),new Set(holdings.filter(p=>p.instrumentId===instrument("EMBR3")).flatMap(p=>p.provenance.operationIds)));
 }finally{await new Promise<void>(resolve=>server.close(()=>resolve()));await db.end();}
});
