import{useEffect,useState}from"react";import{ArrowRight,ChartDonut,CheckCircle,Info,WarningCircle}from"@phosphor-icons/react";import{api}from"../api";import{navigate}from"../components/AppShell";import type{DashboardSummary,AllocationBreakdown,Insight}from"../../../../packages/contracts/src/intelligence";
function useDashboard(){const[data,setData]=useState<DashboardSummary|null>(null),[error,setError]=useState("");useEffect(()=>{api<DashboardSummary>("/v1/dashboard").then(setData).catch(e=>setError(e.message))},[]);return{data,error}}
type HistorySeries={currency:string;status:"AVAILABLE"|"INSUFFICIENT_HISTORY";points:Array<{id:string;knownValue:string;asOf:string;coverageAvailable:number;coverageTotal:number}>};
function useHistory(){const[data,setData]=useState<{series:HistorySeries[]}|null>(null),[error,setError]=useState("");useEffect(()=>{api<{series:HistorySeries[]}>("/v1/dashboard/valuation-history").then(setData).catch(e=>setError(e.message))},[]);return{data,error}}
function Header({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <header className="content-header"><div><p className="kicker">{kicker}</p><h1>{title}</h1><p>{copy}</p></div></header>}
function Load({error}:{error:string}){return error?<div className="state" role="alert"><WarningCircle size={24}/><h3>Dados indisponíveis</h3><p>A API e o PostgreSQL precisam estar ativos para esta visão.</p></div>:<div className="skeleton" role="status" aria-label="Carregando inteligência"/>}
function Buckets({data}:{data:DashboardSummary}){return <div className="executive-grid">{data.portfolio.currencyBuckets.map(b=><section className="executive-currency" key={b.currency}><div><span className="summary-label">Valor conhecido</span><strong>{b.knownMarketValue.status==="AVAILABLE"?b.knownMarketValue.value:"knownValue"in b.knownMarketValue?b.knownMarketValue.knownValue:"Indisponível"} <small>{b.currency}</small></strong></div><div className="executive-coverage"><span>{b.knownMarketValue.coverage.availableComponents} de {b.knownMarketValue.coverage.totalComponents} avaliadas</span><span>{b.knownMarketValue.status}</span></div></section>)}</div>}
function Allocation({item}:{item:AllocationBreakdown}){return <section className="section allocation-section"><div className="section-head"><h2>{item.dimension==="STRATEGY"?"Distribuição por Strategy":"Distribuição por tipo"} · {item.currency}</h2><p>Valor conhecido · cobertura {item.coverage.availableComponents}/{item.coverage.totalComponents}</p></div>{item.items.length?<div className="allocation-list" role="list" aria-label={`Distribuição do valor conhecido em ${item.currency}`}>{item.items.map(x=><div role="listitem" key={x.key}><div><strong>{x.label}</strong><span>{x.positionCount} posição(ões)</span></div><div className="allocation-value"><strong>{x.knownValue} {x.currency}</strong><span>{x.shareOfKnownValue}% do valor conhecido</span></div></div>)}</div>:<div className="state compact"><ChartDonut size={22}/><h3>Sem valuation disponível</h3><p>O gráfico começa quando existir valor econômico observado.</p></div>}</section>}
function History({data,error}:{data:{series:HistorySeries[]}|null;error:string}){const available=data?.series.filter(x=>x.status==="AVAILABLE")??[];return <section className="section"><div className="section-head"><h2>Evolução patrimonial</h2><p>Snapshots observados, sem reconstrução artificial</p></div>{error?<div className="state compact" role="alert"><WarningCircle size={22}/><h3>Histórico indisponível</h3><p>Não foi possível consultar os snapshots observados.</p></div>:available.length?<div className="history-list" role="list">{available.map(series=><div role="listitem" key={series.currency}><strong>{series.currency}</strong><span>{series.points.length} snapshots observados</span></div>)}</div>:<div className="state compact"><Info size={22}/><h3>Histórico ainda insuficiente</h3><p>São necessários ao menos dois snapshots reais por moeda. Nenhum ponto foi fabricado.</p></div>}</section>}
function InsightList({items,limit}:{items:Insight[];limit?:number}){return <div className="insight-list">{items.slice(0,limit).map(i=><article key={i.id}><div><span className={`insight-severity ${i.severity.toLowerCase()}`}>{i.severity==="ATTENTION"?"Atenção":"Informação"}</span><h3>{i.title}</h3><p>{i.summary}</p><small>{i.suggestedReview}</small></div><button className="icon-button" aria-label={`Revisar: ${i.title}`} onClick={()=>navigate(i.href)}><ArrowRight size={17}/></button></article>)}{!items.length&&<div className="state compact"><CheckCircle size={22}/><h3>Nenhum insight ativo</h3><p>Não há regras determinísticas acionadas pelos dados atuais.</p></div>}</div>}
export function DashboardPage(){const{data,error}=useDashboard();return <><Header kicker="Visão executiva" title="Dashboard" copy="Patrimônio conhecido, cobertura e saúde dos dados em uma leitura macro."/>{!data?<Load error={error}/>:<><Buckets data={data}/><section className="health-band"><div><span className="summary-label">Saúde da carteira</span><strong>{data.health.valuationCoverage.available}/{data.health.valuationCoverage.total}</strong><small>posições com valuation</small></div><button onClick={()=>navigate("/portfolio")}><Info size={18}/><span>{data.health.missingValuationCount} valuations pendentes</span><ArrowRight size={16}/></button><button onClick={()=>navigate("/connections")}><span>{data.connectionHealth.active} conexões ativas</span><ArrowRight size={16}/></button></section>{data.allocations.filter(x=>x.dimension==="STRATEGY").map(x=><Allocation key={`${x.dimension}:${x.currency}`} item={x}/>)}<section className="section"><div className="section-head"><h2>Insights prioritários</h2><p>Regras explicáveis, sem recomendação de trade</p></div><InsightList items={data.insights} limit={3}/></section></>}</>}
export function AnalyticsPage(){const{data,error}=useDashboard(),history=useHistory();return <><Header kicker="Drill-down" title="Analytics" copy="Distribuições conhecidas, exposições e cobertura sem fabricar completude."/>{!data?<Load error={error}/>:<>{data.allocations.map(x=><Allocation key={`${x.dimension}:${x.currency}`} item={x}/>)}<History data={history.data} error={history.error}/></>}</>}
export function InsightsPage(){const{data,error}=useDashboard();return <><Header kicker="Explicável" title="Insights" copy="Sinais determinísticos para revisão, nunca instruções de compra ou venda."/>{!data?<Load error={error}/>:<InsightList items={data.insights}/>}</>}
