import{randomUUID}from"node:crypto";import type{PoolClient}from"pg";
type Db=Pick<PoolClient,"query">;
export async function createConnection(db:Db,input:{providerKey:string;displayName:string;capabilities:string[]}){const id=randomUUID();await db.query(`INSERT INTO connections(id,provider_key,display_name,capabilities)VALUES($1,$2,$3,$4::jsonb)`,[id,input.providerKey,input.displayName,JSON.stringify(input.capabilities)]);return id}
export async function listConnections(db:Db){const r=await db.query(`SELECT c.id,c.provider_key,c.display_name,c.status,c.read_only,c.capabilities,c.last_sync_at,EXISTS(SELECT 1 FROM connection_secrets s WHERE s.connection_id=c.id AND s.revoked_at IS NULL) has_credential FROM connections c ORDER BY c.created_at`);return r.rows.map((x:any)=>({id:x.id,providerKey:x.provider_key,displayName:x.display_name,status:x.status,readOnly:x.read_only,capabilities:x.capabilities,lastSyncAt:x.last_sync_at,hasCredential:x.has_credential}))}
export async function findConnection(db:Db,id:string){const r=await db.query(`SELECT id,provider_key,display_name,status,read_only,capabilities,last_sync_at FROM connections WHERE id=$1`,[id]);return r.rows[0]??null}
export async function upsertSecret(db:Db,connectionId:string,value:{ciphertext:Buffer;iv:Buffer;authTag:Buffer;keyVersion:number}){await db.query(`INSERT INTO connection_secrets(id,connection_id,ciphertext,iv,auth_tag,key_version)VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(connection_id)DO UPDATE SET ciphertext=EXCLUDED.ciphertext,iv=EXCLUDED.iv,auth_tag=EXCLUDED.auth_tag,key_version=EXCLUDED.key_version,revoked_at=NULL,rotated_at=NOW()`,[randomUUID(),connectionId,value.ciphertext,value.iv,value.authTag,value.keyVersion])}
export async function revokeSecret(db:Db,connectionId:string){const r=await db.query(`UPDATE connection_secrets SET revoked_at=NOW() WHERE connection_id=$1 AND revoked_at IS NULL`,[connectionId]);return(r.rowCount??0)>0}
export async function createSyncRun(db:Db,connectionId:string){const id=randomUUID();await db.query(`INSERT INTO sync_runs(id,connection_id,status)VALUES($1,$2,'RUNNING')`,[id,connectionId]);return id}
export async function completeSyncRun(db:Db,id:string,c:{fetched:number;imported:number;duplicate:number;ready:number;pending:number;rejected:number}){await db.query(`UPDATE sync_runs SET status='COMPLETED',completed_at=NOW(),fetched_count=$2,imported_count=$3,duplicate_count=$4,ready_count=$5,pending_count=$6,rejected_count=$7 WHERE id=$1`,[id,c.fetched,c.imported,c.duplicate,c.ready,c.pending,c.rejected])}
export async function failSyncRun(db:Db,id:string,code:string){await db.query(`UPDATE sync_runs SET status='FAILED',completed_at=NOW(),error_code=$2 WHERE id=$1`,[id,code])}
export async function listSyncRuns(db:Db){const r=await db.query(`SELECT id,connection_id,status,started_at,completed_at,CASE WHEN completed_at IS NULL THEN NULL ELSE ROUND(EXTRACT(EPOCH FROM(completed_at-started_at))*1000)::int END duration_ms,fetched_count,imported_count,duplicate_count,ready_count,pending_count,rejected_count,error_code FROM sync_runs ORDER BY started_at DESC`);return r.rows.map((x:any)=>({id:x.id,connectionId:x.connection_id,status:x.status,startedAt:x.started_at,completedAt:x.completed_at,durationMs:x.duration_ms,fetched:x.fetched_count,imported:x.imported_count,duplicate:x.duplicate_count,ready:x.ready_count,pending:x.pending_count,rejected:x.rejected_count,errorCode:x.error_code}))}
export async function insertStaging(db:Db,input:{connectionId:string;syncRunId:string;externalId:string|null;fingerprint:string;sanitized:Record<string,string>;normalized:Record<string,string|null>;issues:string[];strategyId:string|null;instrumentId:string|null;accountId:string|null;status:"PENDING"|"READY"|"REJECTED"}){const id=randomUUID();const r=await db.query(`INSERT INTO staging_records(id,connection_id,sync_run_id,external_id,fingerprint,status,sanitized_source,normalized,issues,strategy_id,instrument_id,account_id)VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9::jsonb,$10,$11,$12) ON CONFLICT DO NOTHING RETURNING id`,[id,input.connectionId,input.syncRunId,input.externalId,input.fingerprint,input.status,JSON.stringify(input.sanitized),JSON.stringify(input.normalized),JSON.stringify(input.issues),input.strategyId,input.instrumentId,input.accountId]);if(r.rowCount)return"INSERTED";const existing=await db.query<{fingerprint:string}>(`SELECT fingerprint FROM staging_records WHERE connection_id=$1 AND (fingerprint=$2 OR ($3::varchar IS NOT NULL AND external_id=$3)) LIMIT 1`,[input.connectionId,input.fingerprint,input.externalId]);if(existing.rows[0]?.fingerprint===input.fingerprint)return"DUPLICATE";throw new Error("EXTERNAL_ID_CONFLICT")}
export async function listStaging(db:Db){const r=await db.query(`SELECT id,connection_id,sync_run_id,external_id,status,issues,normalized,strategy_id,instrument_id,account_id,canonical_operation_id,created_at FROM staging_records ORDER BY created_at DESC`);return r.rows.map((x:any)=>({id:x.id,connectionId:x.connection_id,syncRunId:x.sync_run_id,externalId:x.external_id,status:x.status,issues:x.issues,normalized:x.normalized,strategyId:x.strategy_id,instrumentId:x.instrument_id,accountId:x.account_id,canonicalOperationId:x.canonical_operation_id,createdAt:x.created_at}))}
export async function findStaging(db:Db,id:string){const r=await db.query(`SELECT * FROM staging_records WHERE id=$1 FOR UPDATE`,[id]);return r.rows[0]??null}
export async function resolveStaging(db:Db,id:string,input:{strategyId:string;instrumentId:string;accountId:string}){const r=await db.query(`UPDATE staging_records SET strategy_id=$2,instrument_id=$3,account_id=$4,status='READY',issues='[]'::jsonb,updated_at=NOW() WHERE id=$1 AND status='PENDING' RETURNING sync_run_id`,[id,input.strategyId,input.instrumentId,input.accountId]);if(r.rowCount)await db.query(`UPDATE sync_runs SET pending_count=GREATEST(0,pending_count-1),ready_count=ready_count+1 WHERE id=$1`,[r.rows[0]!.sync_run_id]);return(r.rowCount??0)>0}
export async function markStaging(db:Db,id:string,status:"IMPORTED"|"REJECTED",expected:"PENDING"|"READY",operationId?:string){const r=await db.query(`UPDATE staging_records SET status=$2,canonical_operation_id=$3,updated_at=NOW() WHERE id=$1 AND status=$4 RETURNING sync_run_id`,[id,status,operationId??null,expected]);if(!r.rowCount)throw new Error("STAGING_NOT_ACTIONABLE");const runId=r.rows[0]!.sync_run_id;if(status==="IMPORTED")await db.query(`UPDATE sync_runs SET imported_count=imported_count+1,ready_count=GREATEST(0,ready_count-1) WHERE id=$1`,[runId]);if(status==="REJECTED")await db.query(`UPDATE sync_runs SET rejected_count=rejected_count+1,pending_count=GREATEST(0,pending_count-$2),ready_count=GREATEST(0,ready_count-$3) WHERE id=$1`,[runId,expected==="PENDING"?1:0,expected==="READY"?1:0])}
